from __future__ import annotations

from enum import StrEnum


class PublicationFailureCode(StrEnum):
    PROJECTION_BINDING_INVALID = "PROJECTION_BINDING_INVALID"
    PROJECTION_TOO_LARGE = "PROJECTION_TOO_LARGE"
    EXACT_JSON_OBJECT_REQUIRED = "EXACT_JSON_OBJECT_REQUIRED"
    DUPLICATE_JSON_KEY = "DUPLICATE_JSON_KEY"
    RAW_OUTPUT_TOO_LARGE = "RAW_OUTPUT_TOO_LARGE"
    CANDIDATE_SCHEMA_INVALID = "CANDIDATE_SCHEMA_INVALID"
    CANDIDATE_BINDING_MISMATCH = "CANDIDATE_BINDING_MISMATCH"
    DUPLICATE_PERMISSION_REFERENCE = "DUPLICATE_PERMISSION_REFERENCE"
    UNKNOWN_PERMISSION_REFERENCE = "UNKNOWN_PERMISSION_REFERENCE"
    PERMISSION_NOT_ALLOWED = "PERMISSION_NOT_ALLOWED"
    CLAIM_KIND_NOT_PUBLISHABLE = "CLAIM_KIND_NOT_PUBLISHABLE"
    SUBJECT_UNRESOLVED = "SUBJECT_UNRESOLVED"
    SUPPORT_REFERENCE_UNRESOLVED = "SUPPORT_REFERENCE_UNRESOLVED"
    OBLIGATION_REFERENCE_UNRESOLVED = "OBLIGATION_REFERENCE_UNRESOLVED"
    PUBLICATION_OBLIGATION_UNSATISFIED = "PUBLICATION_OBLIGATION_UNSATISFIED"
    COMPARISON_SEMANTICS_MISMATCH = "COMPARISON_SEMANTICS_MISMATCH"
    PERMISSION_SEMANTICS_CHANGED = "PERMISSION_SEMANTICS_CHANGED"
    RENDER_PLAN_INVALID = "RENDER_PLAN_INVALID"
    FINAL_EGRESS_BLOCKED = "FINAL_EGRESS_BLOCKED"
    FALLBACK_UNAVAILABLE = "FALLBACK_UNAVAILABLE"
    BOUNDED_INTERNAL_FAILURE = "BOUNDED_INTERNAL_FAILURE"


class PublicationBoundaryError(ValueError):
    """Bounded deterministic publication failure without untrusted payload text."""

    def __init__(self, code: PublicationFailureCode) -> None:
        self.code = code
        super().__init__(code.value)


class CandidateParseError(PublicationBoundaryError):
    pass
