from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[3]
SOURCE_ROOT = PROJECT_ROOT / "src"
CANONICAL_SCHEMA = PROJECT_ROOT / "protocols" / "hardware" / "v1" / "hardware-tool.schema.json"
OUTPUT = PROJECT_ROOT / "extensions" / "deepseek-harness" / "src" / "generated" / "hardware-tools.generated.ts"

sys.path.insert(0, str(SOURCE_ROOT))

from ai_instrument_assistant.integrations.deepseek_harness.schema_projection import (  # noqa: E402
    project_hardware_tools,
)


def render() -> str:
    canonical_bytes = CANONICAL_SCHEMA.read_bytes()
    canonical = json.loads(canonical_bytes)
    contracts = project_hardware_tools(canonical)
    payload = [
        {
            "harnessName": contract.harness_name,
            "canonicalOperation": contract.canonical_operation,
            "parametersSchema": contract.parameters_schema,
            "outputSchema": contract.output_schema,
            "deferredConstraints": [
                {
                    "jsonPath": constraint.json_path,
                    "keyword": constraint.keyword,
                    "value": constraint.value,
                    "enforcedBy": constraint.enforced_by,
                }
                for constraint in contract.deferred_constraints
            ],
        }
        for contract in contracts
    ]
    rendered = json.dumps(payload, ensure_ascii=True, indent=2, sort_keys=True)
    digest = hashlib.sha256(canonical_bytes).hexdigest()
    return (
        "// Generated by scripts/generate-contracts.py from the canonical Hardware Tool Schema.\n"
        "// Do not edit by hand.\n"
        f'export const CANONICAL_HARDWARE_SCHEMA_SHA256 = "{digest}" as const;\n\n'
        f"export const HARDWARE_TOOL_CONTRACTS = {rendered} as const;\n\n"
        "export type HarnessToolContract = (typeof HARDWARE_TOOL_CONTRACTS)[number];\n"
        "export type HarnessToolName = HarnessToolContract[\"harnessName\"];\n"
        "export type HardwareOperation = HarnessToolContract[\"canonicalOperation\"];\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print("Generated Harness hardware contracts are stale.", file=sys.stderr)
            return 1
        print("Generated Harness hardware contracts match the canonical schema.")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT.relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
